#!/usr/bin/env node
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const sharing=require("../firebase-sharing.js"),courtTimers=require("../court-timers.js"),roundTimer=require("../round-timer.js");
function appState(){return {mode:"ladder",n:8,courts:2,maxPoints:21,endMode:"time",roundDurationMinutes:10,matchIndex:0,tournamentStatus:"live",sharedTournament:null,clubId:"club-a",players:Array.from({length:8},(_,id)=>({name:`J${id+1}`,mj:0,v:0,plus:0,minus:0})),schedule:[{rest:[],courts:[{teamA:[0,1],teamB:[2,3]},{teamA:[4,5],teamB:[6,7]}]}],results:[],validatedCourts:[false,false],courtScores:[]};}
function harness(url="https://brudergeoffrey-byte.github.io/la-team/",authUid="owner-1"){
 const documents=new Map(),subdocuments=new Map(),listeners=new Map(),storage=new Map(),events={},statuses=[];let authCalls=0,serverNow=1700000000000;const navigator={onLine:true};
 const resolve=value=>value&&value.__serverTimestamp?serverNow:Array.isArray(value)?value.map(resolve):value&&typeof value==="object"?Object.fromEntries(Object.entries(value).map(([k,v])=>[k,resolve(v)])):value;
 const valueAt=ref=>ref._root?documents.get(ref._code):subdocuments.get(ref._path),storeAt=(ref,value)=>{const copy=JSON.parse(JSON.stringify(resolve(value)));if(ref._root)documents.set(ref._code,copy);else subdocuments.set(ref._path,copy);listeners.get(ref._path)?.(copy,false);};
 const makeCollection=path=>({doc(id){return makeDoc(`${path}/${id}`,!path.includes("/"));},onSnapshot(options,next){const prefix=`${path}/`,emit=()=>next({docs:[...subdocuments.entries()].filter(([k])=>k.startsWith(prefix)&&!k.slice(prefix.length).includes("/")).map(([k,v])=>({id:k.slice(prefix.length),data:()=>v})),metadata:{fromCache:false}});emit();return()=>{};}});
 const makeDoc=(path,rootDoc=false)=>{const code=path.split("/")[1];return {_path:path,_code:code,_root:rootDoc,async set(value){if(!navigator.onLine)throw new Error("offline");storeAt(this,value);},async get(){const value=valueAt(this);return {exists:value!==undefined,data:()=>value};},onSnapshot(options,next){listeners.set(path,(value,fromCache)=>next({exists:value!==undefined,data:()=>value,metadata:{fromCache}}));const value=valueAt(this);if(value!==undefined)listeners.get(path)(value,false);return()=>listeners.delete(path);},collection(name){return makeCollection(`${path}/${name}`);}};};
 const db={enablePersistence:async()=>{},collection:name=>makeCollection(name),async runTransaction(callback){const writes=[];const result=await callback({async get(ref){const value=valueAt(ref);return {exists:value!==undefined,data:()=>value};},set(ref,value){writes.push([ref,value]);}});for(const [ref,value]of writes)storeAt(ref,value);return result;}};
 const auth={currentUser:url.includes("?t=")?null:{uid:authUid,email:"owner@example.test",isAnonymous:false},onAuthStateChanged(callback){callback(this.currentUser);return()=>{};},async signInAnonymously(){authCalls++;this.currentUser={uid:authUid,isAnonymous:true};return {user:this.currentUser};}};
 const firestore=()=>db;firestore.FieldValue={serverTimestamp:()=>({__serverTimestamp:true})};const firebase={apps:[{}],firestore,auth:()=>auth},document={querySelector(){return null;},createElement(){return {};},head:{appendChild(){}}};
 const context={console,URL,Date,Math,JSON,Promise,Error,Object,Array,String,Number,Boolean,RegExp,LaTeamSharing:sharing,LaTeamCourtTimers:courtTimers,LaTeamRoundTimer:roundTimer,firebase,document,navigator,location:{href:url},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)},addEventListener:(n,f)=>{events[n]=f;},setTimeout:f=>(f(),1),clearTimeout(){}};context.window=context;context.globalThis=context;vm.createContext(context);vm.runInContext(fs.readFileSync(path.resolve(__dirname,"../firebase-client.js"),"utf8"),context);
 return {context,documents,subdocuments,storage,events,statuses,navigator,setServerNow:v=>{serverNow=v;},getAuthCalls:()=>authCalls};
}
(async()=>{
 const original=sharing.randomCode,codes=["ABCD","K7F2"];sharing.randomCode=()=>codes.shift();const h=harness(),state=appState();h.documents.set("ABCD",{collision:true});h.documents.set("club-a",{ownerUid:"owner-1",name:"Club A"});h.context.LaTeamCloud.init({getState:()=>state,onShareStatus:s=>h.statuses.push(s)});const share=await h.context.LaTeamCloud.createSharedTournament();sharing.randomCode=original;assert.equal(share.code,"K7F2");assert.equal(h.getAuthCalls(),0);
 state.results=[[{a:15,b:6},{a:8,b:13}]];state.validatedCourts=[true,true];await h.context.LaTeamCloud.publishNow();h.navigator.onLine=false;state.players[0].name="Remplaçant";assert.equal(await h.context.LaTeamCloud.publishNow(),false);h.navigator.onLine=true;await h.events.online();await new Promise(r=>setImmediate(r));assert.equal(h.documents.get(share.code).players[0].name,"Remplaçant");
 const organizer=await h.context.LaTeamCloud.startRoundTimer({code:share.code,playerId:null});assert.equal(organizer.startedBy,"organizer");assert.equal(organizer.roundStartedAt,1700000000000);assert.equal((await h.context.LaTeamCloud.startRoundTimer({code:share.code,playerId:null})).roundStartedAt,organizer.roundStartedAt);h.setServerNow(1700000005000);assert.equal((await h.context.LaTeamCloud.resetRoundTimer({code:share.code})).state,"idle");
 const viewer=harness(`https://brudergeoffrey-byte.github.io/la-team/?t=${share.code}`,"viewer-1");viewer.documents.set(share.code,h.documents.get(share.code));let received=null,receivedTimer=null;viewer.context.LaTeamCloud.init({getState:()=>appState(),onViewerSnapshot:s=>{received=s;},onRoundTimer:t=>{receivedTimer=t;},onViewerError:m=>{throw new Error(m);}});await new Promise(r=>setImmediate(r));assert.ok(received);
 const started=await viewer.context.LaTeamCloud.startRoundTimer({code:share.code,playerId:0});assert.equal(started.startedBy,0);assert.equal(receivedTimer.roundStartedAt,started.roundStartedAt);
 const viewer2=harness(`https://brudergeoffrey-byte.github.io/la-team/?t=${share.code}`,"viewer-2");viewer2.documents.set(share.code,h.documents.get(share.code));viewer2.subdocuments.set(`tournaments/${share.code}/roundTimer/current`,started);viewer2.setServerNow(1700000010000);assert.equal((await viewer2.context.LaTeamCloud.startRoundTimer({code:share.code,playerId:1})).roundStartedAt,started.roundStartedAt,"deux joueurs convergent vers le premier démarrage");await assert.rejects(()=>viewer.context.LaTeamCloud.resetRoundTimer({code:share.code}),/compte Organisateur/i);
 const late=harness(`https://brudergeoffrey-byte.github.io/la-team/?t=${share.code}`,"viewer-late");late.documents.set(share.code,h.documents.get(share.code));late.subdocuments.set(`tournaments/${share.code}/roundTimer/current`,started);let lateTimer=null;late.context.LaTeamCloud.init({getState:()=>appState(),onViewerSnapshot(){},onRoundTimer:t=>{lateTimer=t;}});await new Promise(r=>setImmediate(r));assert.equal(lateTimer.roundStartedAt,started.roundStartedAt,"arrivée tardive et réouverture");
 console.log("FIREBASE_CLIENT_OK — chrono global, concurrence, reprise réseau et synchronisation temps réel validés");
})().catch(error=>{console.error(error);process.exitCode=1;});
