#!/usr/bin/env node
const fs=require("node:fs"),path=require("node:path");
const {initializeTestEnvironment,assertSucceeds,assertFails}=require("@firebase/rules-unit-testing");
const {doc,setDoc,getDoc,getDocs,collection,query,orderBy,writeBatch,runTransaction,updateDoc}=require("firebase/firestore");
const projectId="demo-la-team",rules=fs.readFileSync(path.resolve(__dirname,"../firestore.rules"),"utf8"),base=1700000000000;
const club=(id,owner)=>({schemaVersion:1,clubId:id,name:id,ownerUid:owner,memberUids:[owner],status:"active",plan:"free",subscriptionStatus:"inactive",trialEndsAt:null,billingCustomerId:null,playerJoinCode:"ABC234",createdAt:base,updatedAt:base});
const member=uid=>({schemaVersion:1,uid,role:"owner",email:`${uid}@test.invalid`,status:"active",createdAt:base,updatedAt:base});
const event=(clubId,id="eventA")=>({schemaVersion:2,eventId:id,clubId,seasonId:null,tournamentId:null,competitionType:"friendly",name:"King Test",startsAt:base+86400000,plannedEndsAt:null,actualEndedAt:null,timezone:"Europe/Brussels",capacity:4,format:"ladder",courtCount:1,endMode:"time",roundDurationMinutes:15,registeredCount:3,waitingCount:0,guestCount:3,registrationStatus:"open",status:"registration",createdAt:base,updatedAt:base});
function profile(uid,playerId,name){return {schemaVersion:2,playerId,publicId:`LT-${playerId.slice(-4).toUpperCase().padStart(4,"A")}`,ownerUid:uid,displayName:name,normalizedName:name.toLowerCase(),status:"active",createdAt:base,updatedAt:base};}
async function joinClub(db,uid,playerId,name,code="ABC234",clubId="clubA") {const p=profile(uid,playerId,name),batch=writeBatch(db);batch.set(doc(db,`players/${playerId}`),p);batch.set(doc(db,`users/${uid}`),{schemaVersion:2,email:`${uid}@test.invalid`,displayName:name,defaultClubId:clubId,playerId,createdAt:base,updatedAt:base});batch.set(doc(db,`clubs/${clubId}/players/${playerId}`),{schemaVersion:2,clubId,playerId,ownerUid:uid,displayName:name,normalizedName:name.toLowerCase(),membershipStatus:"active",joinedWithCode:code,joinedAt:base,updatedAt:base});return batch.commit();}
async function register(db,uid,playerId,name,clubId="clubA",eventId="eventA"){const er=doc(db,`clubs/${clubId}/events/${eventId}`),field=`registration_${uid}`;await runTransaction(db,async tx=>{const es=await tx.get(er),e=es.data();if(e[field])return;const now=Date.now(),row={schemaVersion:2,registrationId:`player_${playerId}`,eventId,clubId,type:"registered",playerId,displayName:name,normalizedName:name.toLowerCase(),status:"cancelled",linkedPlayerId:null,linkedByUid:null,linkedAt:null,registeredByUid:uid,createdAt:now,updatedAt:now};tx.update(er,{[field]:row,updatedAt:now});});return runTransaction(db,async tx=>{const es=await tx.get(er),e=es.data(),current=e[field];if(current&&current.status!=="cancelled")return current;const status=e.registeredCount<e.capacity?"registered":"waiting",now=Math.max(Date.now(),current.updatedAt+1),row={...current,status,updatedAt:now};tx.update(er,{[field]:row,registeredCount:e.registeredCount+(status==="registered"?1:0),waitingCount:e.waitingCount+(status==="waiting"?1:0),updatedAt:now});return row;});}
async function cancel(db,uid){const er=doc(db,"clubs/clubA/events/eventA"),field=`registration_${uid}`;return runTransaction(db,async tx=>{const es=await tx.get(er),e=es.data(),r=e[field],now=Math.max(Date.now(),r.updatedAt+1);tx.update(er,{[field]:{...r,status:"cancelled",updatedAt:now},registeredCount:e.registeredCount-(r.status==="registered"?1:0),waitingCount:e.waitingCount-(r.status==="waiting"?1:0),updatedAt:now});});}
(async()=>{const env=await initializeTestEnvironment({projectId,firestore:{rules,host:"127.0.0.1",port:8088}});await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await setDoc(doc(db,"clubs/clubA"),club("clubA","ownerA"));await setDoc(doc(db,"clubs/clubA/members/ownerA"),member("ownerA"));await setDoc(doc(db,"clubs/clubA/events/eventA"),event("clubA"));await setDoc(doc(db,"clubs/clubB"),club("clubB","ownerB"));await setDoc(doc(db,"clubs/clubB/members/ownerB"),member("ownerB"));await setDoc(doc(db,"clubs/clubB/events/eventB"),event("clubB","eventB"));});
const dbFor=uid=>env.authenticatedContext(uid,{email:`${uid}@test.invalid`}).firestore(),a=dbFor("userA"),b=dbFor("userB"),intruder=dbFor("intruder"),owner=dbFor("ownerA");
await assertSucceeds(joinClub(a,"userA","plra","Geoffrey"));await assertSucceeds(joinClub(b,"userB","plrb","Thomas"));await assertFails(joinClub(intruder,"intruder","plrx","Intrus","WRONG2"));
await assertSucceeds(getDocs(query(collection(a,"clubs/clubA/events"),orderBy("startsAt","asc"))));await assertFails(getDocs(collection(a,"clubs/clubB/events")));await assertFails(updateDoc(doc(a,"clubs/clubA/events/eventA"),{capacity:99}));
const results=await Promise.all([assertSucceeds(register(a,"userA","plra","Geoffrey")),assertSucceeds(register(b,"userB","plrb","Thomas"))]);if(results.filter(x=>x.status==="registered").length!==1||results.filter(x=>x.status==="waiting").length!==1)throw new Error("La dernière place n’a pas été arbitrée atomiquement");
let es=await getDoc(doc(owner,"clubs/clubA/events/eventA"));if(es.data().registeredCount!==4||es.data().waitingCount!==1)throw new Error("Capacité dépassée ou compteur incohérent");
await assertSucceeds(register(a,"userA","plra","Geoffrey"));const current=(await getDoc(doc(owner,"clubs/clubA/events/eventA"))).data();await assertFails(updateDoc(doc(a,"clubs/clubA/events/eventA"),{registration_userB:{...current.registration_userB,registeredByUid:"userA"},updatedAt:Date.now()+1000}));
const winner=results[0].status==="registered"?{db:a,uid:"userA"}:{db:b,uid:"userB"};await assertSucceeds(cancel(winner.db,winner.uid));
es=await getDoc(doc(owner,"clubs/clubA/events/eventA"));if(es.data().registeredCount!==3)throw new Error("Désinscription non atomique");
const guestId="guest_safe",guestRef=doc(owner,`clubs/clubA/events/eventA/registrations/${guestId}`),eventRef=doc(owner,"clubs/clubA/events/eventA");await assertSucceeds(runTransaction(owner,async tx=>{const s=await tx.get(eventRef),e=s.data(),now=Date.now()+2000;tx.set(guestRef,{schemaVersion:2,registrationId:guestId,eventId:"eventA",clubId:"clubA",type:"guest",playerId:null,displayName:"Invité",normalizedName:"invite",status:"registered",linkedPlayerId:null,linkedByUid:null,linkedAt:null,registeredByUid:"ownerA",createdAt:now,updatedAt:now});tx.update(eventRef,{registeredCount:e.registeredCount+1,waitingCount:e.waitingCount,guestCount:e.guestCount+1,updatedAt:now});}));
const guest=await getDoc(guestRef);if(guest.data().playerId!==null||guest.data().type!=="guest")throw new Error("Un invité a reçu un profil permanent");
const anon=env.unauthenticatedContext().firestore();await assertFails(getDocs(collection(anon,"clubs/clubA/events")));await assertFails(setDoc(doc(anon,"clubs/clubA/events/eventA/registrations/player_fake"),{}));
await env.cleanup();console.log("SPARK_REGISTRATION_OK — adhésion par code, concurrence 4/4, attente, idempotence, désinscription, invité et isolation validés");})().catch(e=>{console.error(e);process.exit(1);});
